"""HOOPS AI - Agent Constants & Metadata"""

AGENTS = {
    "assistant_coach": {
        "name": "Assistant Coach",
        "icon": "sports",
        "color": "#f48c25",
        "description": "Team leadership, practice planning, and management strategies.",
        "keywords": ["practice", "plan", "practice plan", "training plan", "session", "workout plan",
                      "team", "manage", "leadership", "organization", "season", "coaching",
                      "warm up", "warmup", "cooldown", "rotation",
                      "אימון", "תכנון", "תוכנית", "מערך", "מערך אימון", "סשן", "מתכנן",
                      "ניהול", "עונה", "אימונים", "חימום"],
    },
    "team_manager": {
        "name": "Team Manager",
        "icon": "calendar_month",
        "color": "#60A5FA",
        "description": "Schedule, calendar, facilities, players, logistics, and billing.",
        "keywords": ["schedule", "calendar", "facility", "logistics", "roster", "event", "venue", "booking",
                      "attendance", "who is", "player list", "who played",
                      "game report", "result", "score", "record", "win", "loss",
                      "upcoming", "next game", "next practice",
                      "payment", "billing", "charge", "paid", "unpaid", "overdue", "debt", "fee", "invoice",
                      "money", "cost", "owe", "collection",
                      "רשימה", "הרכב", "לוח", "אולם", "מגרש", "מתי", "נוכחות",
                      "איפה", "אירוע", "מתקן", "מועדון", "דוח", "דוחות", "תוצאה", "תוצאות",
                      "ניצחון", "הפסד", "משחק", "לוז",
                      "תשלום", "חיוב", "שילם", "שילמו", "חוב", "חובות", "כסף", "גבייה", "תשלומים"],
    },
    "tactician": {
        "name": "The Tactician",
        "icon": "schema",
        "color": "#F87171",
        "description": "Game strategy, plays, X's & O's, and tactical analysis.",
        "keywords": ["play", "strategy", "offense", "defense", "tactic", "formation", "zone", "press", "screen", "pick",
                      "משחקון", "אסטרטגיה", "התקפה", "הגנה", "טקטיקה", "זון"],
    },
    "skills_coach": {
        "name": "Personal Skills Coach",
        "icon": "fitness_center",
        "color": "#34D399",
        "description": "Personal skill development, technique, and individual training (ages 13+).",
        "keywords": ["drill", "skill", "technique", "shooting", "dribble", "passing", "footwork", "individual",
                      "personal development", "ball handling", "improve", "weakness", "player development",
                      "תרגיל", "טכניקה", "זריקה", "כדרור", "מסירה", "יכולות", "יכולת",
                      "פיתוח", "אישי", "אישית", "חולשה", "חיזוק"],
    },
    "nutritionist": {
        "name": "Sports Nutritionist",
        "icon": "restaurant",
        "color": "#FBBF24",
        "description": "Nutrition plans, diet advice, hydration, and recovery meals.",
        "keywords": ["food", "diet", "nutrition", "meal", "hydration", "protein", "supplement", "eat", "weight",
                      "תזונה", "אוכל", "דיאטה", "ארוחה", "שתייה"],
    },
    "strength_coach": {
        "name": "Strength & Conditioning",
        "icon": "exercise",
        "color": "#A78BFA",
        "description": "Athletic performance, workouts, conditioning, and injury prevention.",
        "keywords": ["workout", "strength", "conditioning", "agility", "speed", "jump", "endurance", "fitness", "injury",
                      "כושר", "חיזוק", "פציעה", "מהירות", "קפיצה"],
    },
    "analyst": {
        "name": "The Analyst",
        "icon": "analytics",
        "color": "#2DD4BF",
        "description": "Statistics, performance analytics, financial analysis, and data-driven insights.",
        "keywords": ["stat", "analytics", "data", "performance", "percentage", "chart", "compare", "trend", "metric",
                      "billing", "payment", "paid", "unpaid", "overdue", "debt", "collection",
                      "סטטיסטיקה", "נתונים", "ביצועים", "אחוז", "השוואה",
                      "תשלום", "חיוב", "שילם", "שילמו", "חוב", "חובות", "גבייה"],
    },
    "youth_coach": {
        "name": "Youth & Age Groups Coach",
        "icon": "child_care",
        "color": "#FB923C",
        "description": "Basketball development for young age groups (ages 5-12).",
        "keywords": ["kid", "child", "young", "beginner", "fun", "youth", "u10", "u8", "u12", "u14", "age group",
                      "junior", "mini basketball", "mini hoops",
                      "ילד", "ילדים", "צעיר", "מתחיל", "כיף", "שכבה", "שכבות", "נוער", "ג'וניור"],
    },
}

AGENT_KEYS = list(AGENTS.keys())
