"""HOOPS AI - Agent Constants & Metadata"""

AGENTS = {
    "assistant_coach": {
        "name": "Assistant Coach",
        "icon": "sports",
        "color": "#f48c25",
        "description": "Team leadership, practice planning, and management strategies.",
        "keywords": ["practice", "plan", "team", "manage", "leadership", "organization", "season", "coaching",
                      "אימון", "תכנון", "ניהול", "עונה", "אימונים"],
    },
    "team_manager": {
        "name": "Team Manager",
        "icon": "calendar_month",
        "color": "#60A5FA",
        "description": "Schedule, calendar, facilities, players, logistics, and billing.",
        "keywords": ["schedule", "calendar", "facility", "logistics", "roster", "event", "venue", "booking",
                      "player", "players", "attendance", "who", "list",
                      "game report", "report", "result", "score", "record", "win", "loss",
                      "upcoming", "next game", "next practice",
                      "payment", "billing", "charge", "paid", "unpaid", "overdue", "debt", "fee", "invoice",
                      "money", "cost", "owe", "collection",
                      "שחקן", "שחקנים", "רשימ", "הרכב", "לוח", "אולם", "מגרש", "מתי", "נוכחות",
                      "איפה", "אירוע", "מתקן", "מועדון", "דוח", "דוחות", "תוצאה", "תוצאות",
                      "ניצחון", "הפסד", "משחק", "משחקים", "מצב", "סטטוס", "לוז",
                      "תשלום", "חיוב", "שילם", "שילמו", "חוב", "חובות", "כסף", "גבייה", "תשלומים"],
    },
    "tactician": {
        "name": "The Tactician",
        "icon": "schema",
        "color": "#F87171",
        "description": "Game strategy, plays, X's & O's, and tactical analysis.",
        "keywords": ["play", "strategy", "offense", "defense", "tactic", "formation", "zone", "press", "screen", "pick",
                      "משחקון", "אסטרטגיה", "התקפה", "הגנה", "טקטיקה", "זון"],
    },
    "skills_coach": {
        "name": "Skills Coach",
        "icon": "fitness_center",
        "color": "#34D399",
        "description": "Training drills, technique improvement, and skill development (ages 13+).",
        "keywords": ["drill", "skill", "technique", "shooting", "dribble", "passing", "footwork", "training",
                      "תרגיל", "טכניקה", "זריקה", "כדרור", "מסירה"],
    },
    "nutritionist": {
        "name": "Sports Nutritionist",
        "icon": "restaurant",
        "color": "#FBBF24",
        "description": "Nutrition plans, diet advice, hydration, and recovery meals.",
        "keywords": ["food", "diet", "nutrition", "meal", "hydration", "protein", "supplement", "eat", "weight",
                      "תזונה", "אוכל", "דיאטה", "ארוחה", "שתייה"],
    },
    "strength_coach": {
        "name": "Strength & Conditioning",
        "icon": "exercise",
        "color": "#A78BFA",
        "description": "Athletic performance, workouts, conditioning, and injury prevention.",
        "keywords": ["workout", "strength", "conditioning", "agility", "speed", "jump", "endurance", "fitness", "injury",
                      "כושר", "חיזוק", "פציעה", "מהירות", "קפיצה"],
    },
    "analyst": {
        "name": "The Analyst",
        "icon": "analytics",
        "color": "#2DD4BF",
        "description": "Statistics, performance analytics, financial analysis, and data-driven insights.",
        "keywords": ["stat", "analytics", "data", "performance", "percentage", "chart", "compare", "trend", "metric",
                      "billing", "payment", "paid", "unpaid", "overdue", "debt", "collection",
                      "סטטיסטיקה", "נתונים", "ביצועים", "אחוז", "השוואה",
                      "תשלום", "חיוב", "שילם", "שילמו", "חוב", "חובות", "גבייה"],
    },
    "youth_coach": {
        "name": "Youth Coach",
        "icon": "child_care",
        "color": "#FB923C",
        "description": "Child-friendly basketball development for ages 5-12.",
        "keywords": ["kid", "child", "young", "beginner", "fun", "youth", "u10", "u8", "u12", "development",
                      "ילד", "ילדים", "צעיר", "מתחיל", "כיף", "משחק ילדים"],
    },
}

AGENT_KEYS = list(AGENTS.keys())
